services:
  
  mysql:
    image: mysql:8.0
    container_name: mysql-mascotas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mascotas
    ports:
      - "3333:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - perrosnet


  backend:
    container_name: backend-perrosenlacalle
    build:
      context: ./perrosenlacalle 
      dockerfile: Dockerfile
    ports:
      - "9088:9088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mascotas?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - perrosnet


  frontend:
    container_name: frontend-perrosenlacalle
    build:
      context: ./encontraTuMascota
      dockerfile: Dockerfile 
    ports:
      - "5173:80"
    networks:
      - perrosnet
    depends_on:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma-mascotas
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - perrosnet

networks:
  perrosnet:
    driver: bridge

volumes:
  mysql_data:
